export type GalleryImage = { src: string; alt?: string };

export const proposalImages: GalleryImage[] = [
  { src: "/proposal-1.jpg", alt: "The Moment" },
  { src: "/proposal-2.jpg", alt: "Preparation" },
  { src: "/proposal-3.jpg", alt: "Nervous Energy" },
  { src: "/proposal-4.jpg", alt: "The Question" },
  { src: "/proposal-5.jpg", alt: "Her Answer" },
  { src: "/proposal-6.jpg", alt: "Celebration" },
  { src: "/proposal-7.jpg", alt: "Together" },
];

export const prenupImages: GalleryImage[] = [
  { src: "/Prenup Photos/LYD_2376.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2399.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2451.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2503.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2528.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2580.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2644.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2647.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2691.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2724.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2730.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2758.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2798.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2814.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2866.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2875.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2884.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2943.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2945.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_2960.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3018.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3032.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3082.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3089.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3128.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3166.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3210.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3238.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3251.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3264.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3355.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3363.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3476.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3518.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3550.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3594.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3638.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3668.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3695.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3704.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3748.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3782.jpg", alt: "Pre-Nup Photo" },
  { src: "/Prenup Photos/LYD_3796.jpg", alt: "Pre-Nup Photo" },
];

export const allImages: GalleryImage[] = [...proposalImages, ...prenupImages];

